// Copyright (c) 2020, Oracle Corporation and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/oracle/verrazzano-crd-generator/pkg/clientcoherence/clientset/versioned/typed/coherence/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCoherenceV1 struct {
	*testing.Fake
}

func (c *FakeCoherenceV1) CoherenceClusters(namespace string) v1.CoherenceClusterInterface {
	return &FakeCoherenceClusters{c, namespace}
}

func (c *FakeCoherenceV1) CoherenceInternals(namespace string) v1.CoherenceInternalInterface {
	return &FakeCoherenceInternals{c, namespace}
}

func (c *FakeCoherenceV1) CoherenceRoles(namespace string) v1.CoherenceRoleInterface {
	return &FakeCoherenceRoles{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCoherenceV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
