// Copyright (c) 2020, Oracle Corporation and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	coherencev1 "github.com/verrazzano/verrazzano-crd-generator/pkg/apis/coherence/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCoherenceInternals implements CoherenceInternalInterface
type FakeCoherenceInternals struct {
	Fake *FakeCoherenceV1
	ns   string
}

var coherenceinternalsResource = schema.GroupVersionResource{Group: "coherence.oracle.com", Version: "v1", Resource: "coherenceinternals"}

var coherenceinternalsKind = schema.GroupVersionKind{Group: "coherence.oracle.com", Version: "v1", Kind: "CoherenceInternal"}

// Get takes name of the coherenceInternal, and returns the corresponding coherenceInternal object, and an error if there is any.
func (c *FakeCoherenceInternals) Get(name string, options v1.GetOptions) (result *coherencev1.CoherenceInternal, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(coherenceinternalsResource, c.ns, name), &coherencev1.CoherenceInternal{})

	if obj == nil {
		return nil, err
	}
	return obj.(*coherencev1.CoherenceInternal), err
}

// List takes label and field selectors, and returns the list of CoherenceInternals that match those selectors.
func (c *FakeCoherenceInternals) List(opts v1.ListOptions) (result *coherencev1.CoherenceInternalList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(coherenceinternalsResource, coherenceinternalsKind, c.ns, opts), &coherencev1.CoherenceInternalList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &coherencev1.CoherenceInternalList{ListMeta: obj.(*coherencev1.CoherenceInternalList).ListMeta}
	for _, item := range obj.(*coherencev1.CoherenceInternalList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested coherenceInternals.
func (c *FakeCoherenceInternals) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(coherenceinternalsResource, c.ns, opts))

}

// Create takes the representation of a coherenceInternal and creates it.  Returns the server's representation of the coherenceInternal, and an error, if there is any.
func (c *FakeCoherenceInternals) Create(coherenceInternal *coherencev1.CoherenceInternal) (result *coherencev1.CoherenceInternal, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(coherenceinternalsResource, c.ns, coherenceInternal), &coherencev1.CoherenceInternal{})

	if obj == nil {
		return nil, err
	}
	return obj.(*coherencev1.CoherenceInternal), err
}

// Update takes the representation of a coherenceInternal and updates it. Returns the server's representation of the coherenceInternal, and an error, if there is any.
func (c *FakeCoherenceInternals) Update(coherenceInternal *coherencev1.CoherenceInternal) (result *coherencev1.CoherenceInternal, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(coherenceinternalsResource, c.ns, coherenceInternal), &coherencev1.CoherenceInternal{})

	if obj == nil {
		return nil, err
	}
	return obj.(*coherencev1.CoherenceInternal), err
}

// Delete takes name of the coherenceInternal and deletes it. Returns an error if one occurs.
func (c *FakeCoherenceInternals) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(coherenceinternalsResource, c.ns, name), &coherencev1.CoherenceInternal{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCoherenceInternals) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(coherenceinternalsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &coherencev1.CoherenceInternalList{})
	return err
}

// Patch applies the patch and returns the patched coherenceInternal.
func (c *FakeCoherenceInternals) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *coherencev1.CoherenceInternal, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(coherenceinternalsResource, c.ns, name, pt, data, subresources...), &coherencev1.CoherenceInternal{})

	if obj == nil {
		return nil, err
	}
	return obj.(*coherencev1.CoherenceInternal), err
}
