// Copyright (c) 2020, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	internalinterfaces "github.com/verrazzano/verrazzano-crd-generator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// VerrazzanoBindings returns a VerrazzanoBindingInformer.
	VerrazzanoBindings() VerrazzanoBindingInformer
	// VerrazzanoManagedClusters returns a VerrazzanoManagedClusterInformer.
	VerrazzanoManagedClusters() VerrazzanoManagedClusterInformer
	// VerrazzanoModels returns a VerrazzanoModelInformer.
	VerrazzanoModels() VerrazzanoModelInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// VerrazzanoBindings returns a VerrazzanoBindingInformer.
func (v *version) VerrazzanoBindings() VerrazzanoBindingInformer {
	return &verrazzanoBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VerrazzanoManagedClusters returns a VerrazzanoManagedClusterInformer.
func (v *version) VerrazzanoManagedClusters() VerrazzanoManagedClusterInformer {
	return &verrazzanoManagedClusterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VerrazzanoModels returns a VerrazzanoModelInformer.
func (v *version) VerrazzanoModels() VerrazzanoModelInformer {
	return &verrazzanoModelInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
