// Copyright (c) 2020, Oracle Corporation and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	verrazzanov1beta1 "github.com/verrazzano/verrazzano-crd-generator/pkg/apis/verrazzano/v1beta1"
	versioned "github.com/verrazzano/verrazzano-crd-generator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/verrazzano/verrazzano-crd-generator/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/verrazzano/verrazzano-crd-generator/pkg/client/listers/verrazzano/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VerrazzanoModelInformer provides access to a shared informer and lister for
// VerrazzanoModels.
type VerrazzanoModelInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.VerrazzanoModelLister
}

type verrazzanoModelInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVerrazzanoModelInformer constructs a new informer for VerrazzanoModel type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVerrazzanoModelInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVerrazzanoModelInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVerrazzanoModelInformer constructs a new informer for VerrazzanoModel type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVerrazzanoModelInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VerrazzanoV1beta1().VerrazzanoModels(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VerrazzanoV1beta1().VerrazzanoModels(namespace).Watch(options)
			},
		},
		&verrazzanov1beta1.VerrazzanoModel{},
		resyncPeriod,
		indexers,
	)
}

func (f *verrazzanoModelInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVerrazzanoModelInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *verrazzanoModelInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&verrazzanov1beta1.VerrazzanoModel{}, f.defaultInformer)
}

func (f *verrazzanoModelInformer) Lister() v1beta1.VerrazzanoModelLister {
	return v1beta1.NewVerrazzanoModelLister(f.Informer().GetIndexer())
}
