// Copyright (c) 2020, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by lister-gen. DO NOT EDIT.

package v1

// CoherenceClusterListerExpansion allows custom methods to be added to
// CoherenceClusterLister.
type CoherenceClusterListerExpansion interface{}

// CoherenceClusterNamespaceListerExpansion allows custom methods to be added to
// CoherenceClusterNamespaceLister.
type CoherenceClusterNamespaceListerExpansion interface{}

// CoherenceInternalListerExpansion allows custom methods to be added to
// CoherenceInternalLister.
type CoherenceInternalListerExpansion interface{}

// CoherenceInternalNamespaceListerExpansion allows custom methods to be added to
// CoherenceInternalNamespaceLister.
type CoherenceInternalNamespaceListerExpansion interface{}

// CoherenceRoleListerExpansion allows custom methods to be added to
// CoherenceRoleLister.
type CoherenceRoleListerExpansion interface{}

// CoherenceRoleNamespaceListerExpansion allows custom methods to be added to
// CoherenceRoleNamespaceLister.
type CoherenceRoleNamespaceListerExpansion interface{}
