// Copyright (c) 2020, Oracle Corporation and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// VerrazzanoBindingListerExpansion allows custom methods to be added to
// VerrazzanoBindingLister.
type VerrazzanoBindingListerExpansion interface{}

// VerrazzanoBindingNamespaceListerExpansion allows custom methods to be added to
// VerrazzanoBindingNamespaceLister.
type VerrazzanoBindingNamespaceListerExpansion interface{}

// VerrazzanoManagedClusterListerExpansion allows custom methods to be added to
// VerrazzanoManagedClusterLister.
type VerrazzanoManagedClusterListerExpansion interface{}

// VerrazzanoManagedClusterNamespaceListerExpansion allows custom methods to be added to
// VerrazzanoManagedClusterNamespaceLister.
type VerrazzanoManagedClusterNamespaceListerExpansion interface{}

// VerrazzanoModelListerExpansion allows custom methods to be added to
// VerrazzanoModelLister.
type VerrazzanoModelListerExpansion interface{}

// VerrazzanoModelNamespaceListerExpansion allows custom methods to be added to
// VerrazzanoModelNamespaceLister.
type VerrazzanoModelNamespaceListerExpansion interface{}
