// Copyright (c) 2020, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by lister-gen. DO NOT EDIT.

package v8

// DomainListerExpansion allows custom methods to be added to
// DomainLister.
type DomainListerExpansion interface{}

// DomainNamespaceListerExpansion allows custom methods to be added to
// DomainNamespaceLister.
type DomainNamespaceListerExpansion interface{}
