// Copyright (c) 2020, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by informer-gen. DO NOT EDIT.

package weblogic

import (
	internalinterfaces "github.com/verrazzano/verrazzano-crd-generator/pkg/clientwks/informers/externalversions/internalinterfaces"
	v7 "github.com/verrazzano/verrazzano-crd-generator/pkg/clientwks/informers/externalversions/weblogic/v7"
)

// Interface provides access to each of this group's versions.
type Interface interface {
	// V7 provides access to shared informers for resources in V7.
	V7() v7.Interface
}

type group struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &group{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// V7 returns a new v7.Interface.
func (g *group) V7() v7.Interface {
	return v7.New(g.factory, g.namespace, g.tweakListOptions)
}
