// Copyright (c) 2020, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by informer-gen. DO NOT EDIT.

package weblogic

import (
	internalinterfaces "github.com/verrazzano/verrazzano-crd-generator/pkg/clientwks/informers/externalversions/internalinterfaces"
	v8 "github.com/verrazzano/verrazzano-crd-generator/pkg/clientwks/informers/externalversions/weblogic/v8"
)

// Interface provides access to each of this group's versions.
type Interface interface {
	// V8 provides access to shared informers for resources in V8.
	V8() v8.Interface
}

type group struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &group{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// V8 returns a new v8.Interface.
func (g *group) V8() v8.Interface {
	return v8.New(g.factory, g.namespace, g.tweakListOptions)
}
