# Copyright (c) 2020, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: verrazzano-crd-generator
subjects:
- kind: ServiceAccount
  name: verrazzano-crd-generator
roleRef:
  kind: Role
  name: verrazzano-crd-generator
  apiGroup: rbac.authorization.k8s.io
