// Copyright (c) 2020, Oracle Corporation and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v1 "github.com/verrazzano/verrazzano-crd-generator/pkg/apis/coherence/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=coherence.oracle.com, Version=v1
	case v1.SchemeGroupVersion.WithResource("coherenceclusters"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Coherence().V1().CoherenceClusters().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("coherenceinternals"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Coherence().V1().CoherenceInternals().Informer()}, nil
	case v1.SchemeGroupVersion.WithResource("coherenceroles"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Coherence().V1().CoherenceRoles().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
