// Copyright (c) 2020, Oracle Corporation and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/oracle/verrazzano-crd-generator/pkg/apis/verrazzano/v1beta1"
	scheme "github.com/oracle/verrazzano-crd-generator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VerrazzanoManagedClustersGetter has a method to return a VerrazzanoManagedClusterInterface.
// A group's client should implement this interface.
type VerrazzanoManagedClustersGetter interface {
	VerrazzanoManagedClusters(namespace string) VerrazzanoManagedClusterInterface
}

// VerrazzanoManagedClusterInterface has methods to work with VerrazzanoManagedCluster resources.
type VerrazzanoManagedClusterInterface interface {
	Create(*v1beta1.VerrazzanoManagedCluster) (*v1beta1.VerrazzanoManagedCluster, error)
	Update(*v1beta1.VerrazzanoManagedCluster) (*v1beta1.VerrazzanoManagedCluster, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.VerrazzanoManagedCluster, error)
	List(opts v1.ListOptions) (*v1beta1.VerrazzanoManagedClusterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.VerrazzanoManagedCluster, err error)
	VerrazzanoManagedClusterExpansion
}

// verrazzanoManagedClusters implements VerrazzanoManagedClusterInterface
type verrazzanoManagedClusters struct {
	client rest.Interface
	ns     string
}

// newVerrazzanoManagedClusters returns a VerrazzanoManagedClusters
func newVerrazzanoManagedClusters(c *VerrazzanoV1beta1Client, namespace string) *verrazzanoManagedClusters {
	return &verrazzanoManagedClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the verrazzanoManagedCluster, and returns the corresponding verrazzanoManagedCluster object, and an error if there is any.
func (c *verrazzanoManagedClusters) Get(name string, options v1.GetOptions) (result *v1beta1.VerrazzanoManagedCluster, err error) {
	result = &v1beta1.VerrazzanoManagedCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("verrazzanomanagedclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VerrazzanoManagedClusters that match those selectors.
func (c *verrazzanoManagedClusters) List(opts v1.ListOptions) (result *v1beta1.VerrazzanoManagedClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.VerrazzanoManagedClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("verrazzanomanagedclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested verrazzanoManagedClusters.
func (c *verrazzanoManagedClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("verrazzanomanagedclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a verrazzanoManagedCluster and creates it.  Returns the server's representation of the verrazzanoManagedCluster, and an error, if there is any.
func (c *verrazzanoManagedClusters) Create(verrazzanoManagedCluster *v1beta1.VerrazzanoManagedCluster) (result *v1beta1.VerrazzanoManagedCluster, err error) {
	result = &v1beta1.VerrazzanoManagedCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("verrazzanomanagedclusters").
		Body(verrazzanoManagedCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a verrazzanoManagedCluster and updates it. Returns the server's representation of the verrazzanoManagedCluster, and an error, if there is any.
func (c *verrazzanoManagedClusters) Update(verrazzanoManagedCluster *v1beta1.VerrazzanoManagedCluster) (result *v1beta1.VerrazzanoManagedCluster, err error) {
	result = &v1beta1.VerrazzanoManagedCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("verrazzanomanagedclusters").
		Name(verrazzanoManagedCluster.Name).
		Body(verrazzanoManagedCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the verrazzanoManagedCluster and deletes it. Returns an error if one occurs.
func (c *verrazzanoManagedClusters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("verrazzanomanagedclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *verrazzanoManagedClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("verrazzanomanagedclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched verrazzanoManagedCluster.
func (c *verrazzanoManagedClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.VerrazzanoManagedCluster, err error) {
	result = &v1beta1.VerrazzanoManagedCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("verrazzanomanagedclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
