// Copyright (c) 2020, Oracle Corporation and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/verrazzano/verrazzano-crd-generator/pkg/apis/verrazzano/v1beta1"
	scheme "github.com/verrazzano/verrazzano-crd-generator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VerrazzanoModelsGetter has a method to return a VerrazzanoModelInterface.
// A group's client should implement this interface.
type VerrazzanoModelsGetter interface {
	VerrazzanoModels(namespace string) VerrazzanoModelInterface
}

// VerrazzanoModelInterface has methods to work with VerrazzanoModel resources.
type VerrazzanoModelInterface interface {
	Create(*v1beta1.VerrazzanoModel) (*v1beta1.VerrazzanoModel, error)
	Update(*v1beta1.VerrazzanoModel) (*v1beta1.VerrazzanoModel, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.VerrazzanoModel, error)
	List(opts v1.ListOptions) (*v1beta1.VerrazzanoModelList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.VerrazzanoModel, err error)
	VerrazzanoModelExpansion
}

// verrazzanoModels implements VerrazzanoModelInterface
type verrazzanoModels struct {
	client rest.Interface
	ns     string
}

// newVerrazzanoModels returns a VerrazzanoModels
func newVerrazzanoModels(c *VerrazzanoV1beta1Client, namespace string) *verrazzanoModels {
	return &verrazzanoModels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the verrazzanoModel, and returns the corresponding verrazzanoModel object, and an error if there is any.
func (c *verrazzanoModels) Get(name string, options v1.GetOptions) (result *v1beta1.VerrazzanoModel, err error) {
	result = &v1beta1.VerrazzanoModel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("verrazzanomodels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VerrazzanoModels that match those selectors.
func (c *verrazzanoModels) List(opts v1.ListOptions) (result *v1beta1.VerrazzanoModelList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.VerrazzanoModelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("verrazzanomodels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested verrazzanoModels.
func (c *verrazzanoModels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("verrazzanomodels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a verrazzanoModel and creates it.  Returns the server's representation of the verrazzanoModel, and an error, if there is any.
func (c *verrazzanoModels) Create(verrazzanoModel *v1beta1.VerrazzanoModel) (result *v1beta1.VerrazzanoModel, err error) {
	result = &v1beta1.VerrazzanoModel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("verrazzanomodels").
		Body(verrazzanoModel).
		Do().
		Into(result)
	return
}

// Update takes the representation of a verrazzanoModel and updates it. Returns the server's representation of the verrazzanoModel, and an error, if there is any.
func (c *verrazzanoModels) Update(verrazzanoModel *v1beta1.VerrazzanoModel) (result *v1beta1.VerrazzanoModel, err error) {
	result = &v1beta1.VerrazzanoModel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("verrazzanomodels").
		Name(verrazzanoModel.Name).
		Body(verrazzanoModel).
		Do().
		Into(result)
	return
}

// Delete takes name of the verrazzanoModel and deletes it. Returns an error if one occurs.
func (c *verrazzanoModels) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("verrazzanomodels").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *verrazzanoModels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("verrazzanomodels").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched verrazzanoModel.
func (c *verrazzanoModels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.VerrazzanoModel, err error) {
	result = &v1beta1.VerrazzanoModel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("verrazzanomodels").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
