// Copyright (c) 2020, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/verrazzano/verrazzano-crd-generator/pkg/apis/coherence/v1"
	scheme "github.com/verrazzano/verrazzano-crd-generator/pkg/clientcoherence/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CoherenceInternalsGetter has a method to return a CoherenceInternalInterface.
// A group's client should implement this interface.
type CoherenceInternalsGetter interface {
	CoherenceInternals(namespace string) CoherenceInternalInterface
}

// CoherenceInternalInterface has methods to work with CoherenceInternal resources.
type CoherenceInternalInterface interface {
	Create(ctx context.Context, coherenceInternal *v1.CoherenceInternal, opts metav1.CreateOptions) (*v1.CoherenceInternal, error)
	Update(ctx context.Context, coherenceInternal *v1.CoherenceInternal, opts metav1.UpdateOptions) (*v1.CoherenceInternal, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.CoherenceInternal, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.CoherenceInternalList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CoherenceInternal, err error)
	CoherenceInternalExpansion
}

// coherenceInternals implements CoherenceInternalInterface
type coherenceInternals struct {
	client rest.Interface
	ns     string
}

// newCoherenceInternals returns a CoherenceInternals
func newCoherenceInternals(c *CoherenceV1Client, namespace string) *coherenceInternals {
	return &coherenceInternals{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the coherenceInternal, and returns the corresponding coherenceInternal object, and an error if there is any.
func (c *coherenceInternals) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.CoherenceInternal, err error) {
	result = &v1.CoherenceInternal{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("coherenceinternals").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CoherenceInternals that match those selectors.
func (c *coherenceInternals) List(ctx context.Context, opts metav1.ListOptions) (result *v1.CoherenceInternalList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CoherenceInternalList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("coherenceinternals").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested coherenceInternals.
func (c *coherenceInternals) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("coherenceinternals").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a coherenceInternal and creates it.  Returns the server's representation of the coherenceInternal, and an error, if there is any.
func (c *coherenceInternals) Create(ctx context.Context, coherenceInternal *v1.CoherenceInternal, opts metav1.CreateOptions) (result *v1.CoherenceInternal, err error) {
	result = &v1.CoherenceInternal{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("coherenceinternals").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(coherenceInternal).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a coherenceInternal and updates it. Returns the server's representation of the coherenceInternal, and an error, if there is any.
func (c *coherenceInternals) Update(ctx context.Context, coherenceInternal *v1.CoherenceInternal, opts metav1.UpdateOptions) (result *v1.CoherenceInternal, err error) {
	result = &v1.CoherenceInternal{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("coherenceinternals").
		Name(coherenceInternal.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(coherenceInternal).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the coherenceInternal and deletes it. Returns an error if one occurs.
func (c *coherenceInternals) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("coherenceinternals").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *coherenceInternals) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("coherenceinternals").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched coherenceInternal.
func (c *coherenceInternals) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CoherenceInternal, err error) {
	result = &v1.CoherenceInternal{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("coherenceinternals").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
