// Copyright (c) 2020, Oracle and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/verrazzano/verrazzano-crd-generator/pkg/apis/coherence/v1"
	scheme "github.com/verrazzano/verrazzano-crd-generator/pkg/clientcoherence/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CoherenceClustersGetter has a method to return a CoherenceClusterInterface.
// A group's client should implement this interface.
type CoherenceClustersGetter interface {
	CoherenceClusters(namespace string) CoherenceClusterInterface
}

// CoherenceClusterInterface has methods to work with CoherenceCluster resources.
type CoherenceClusterInterface interface {
	Create(ctx context.Context, coherenceCluster *v1.CoherenceCluster, opts metav1.CreateOptions) (*v1.CoherenceCluster, error)
	Update(ctx context.Context, coherenceCluster *v1.CoherenceCluster, opts metav1.UpdateOptions) (*v1.CoherenceCluster, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.CoherenceCluster, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.CoherenceClusterList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CoherenceCluster, err error)
	CoherenceClusterExpansion
}

// coherenceClusters implements CoherenceClusterInterface
type coherenceClusters struct {
	client rest.Interface
	ns     string
}

// newCoherenceClusters returns a CoherenceClusters
func newCoherenceClusters(c *CoherenceV1Client, namespace string) *coherenceClusters {
	return &coherenceClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the coherenceCluster, and returns the corresponding coherenceCluster object, and an error if there is any.
func (c *coherenceClusters) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.CoherenceCluster, err error) {
	result = &v1.CoherenceCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("coherenceclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CoherenceClusters that match those selectors.
func (c *coherenceClusters) List(ctx context.Context, opts metav1.ListOptions) (result *v1.CoherenceClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CoherenceClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("coherenceclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested coherenceClusters.
func (c *coherenceClusters) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("coherenceclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a coherenceCluster and creates it.  Returns the server's representation of the coherenceCluster, and an error, if there is any.
func (c *coherenceClusters) Create(ctx context.Context, coherenceCluster *v1.CoherenceCluster, opts metav1.CreateOptions) (result *v1.CoherenceCluster, err error) {
	result = &v1.CoherenceCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("coherenceclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(coherenceCluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a coherenceCluster and updates it. Returns the server's representation of the coherenceCluster, and an error, if there is any.
func (c *coherenceClusters) Update(ctx context.Context, coherenceCluster *v1.CoherenceCluster, opts metav1.UpdateOptions) (result *v1.CoherenceCluster, err error) {
	result = &v1.CoherenceCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("coherenceclusters").
		Name(coherenceCluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(coherenceCluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the coherenceCluster and deletes it. Returns an error if one occurs.
func (c *coherenceClusters) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("coherenceclusters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *coherenceClusters) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("coherenceclusters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched coherenceCluster.
func (c *coherenceClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.CoherenceCluster, err error) {
	result = &v1.CoherenceCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("coherenceclusters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
