// Copyright (c) 2020, Oracle Corporation and/or its affiliates.
// Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/oracle/verrazzano-crd-generator/pkg/apis/coherence/v1"
	scheme "github.com/oracle/verrazzano-crd-generator/pkg/clientcoherence/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CoherenceRolesGetter has a method to return a CoherenceRoleInterface.
// A group's client should implement this interface.
type CoherenceRolesGetter interface {
	CoherenceRoles(namespace string) CoherenceRoleInterface
}

// CoherenceRoleInterface has methods to work with CoherenceRole resources.
type CoherenceRoleInterface interface {
	Create(*v1.CoherenceRole) (*v1.CoherenceRole, error)
	Update(*v1.CoherenceRole) (*v1.CoherenceRole, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.CoherenceRole, error)
	List(opts metav1.ListOptions) (*v1.CoherenceRoleList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CoherenceRole, err error)
	CoherenceRoleExpansion
}

// coherenceRoles implements CoherenceRoleInterface
type coherenceRoles struct {
	client rest.Interface
	ns     string
}

// newCoherenceRoles returns a CoherenceRoles
func newCoherenceRoles(c *CoherenceV1Client, namespace string) *coherenceRoles {
	return &coherenceRoles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the coherenceRole, and returns the corresponding coherenceRole object, and an error if there is any.
func (c *coherenceRoles) Get(name string, options metav1.GetOptions) (result *v1.CoherenceRole, err error) {
	result = &v1.CoherenceRole{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("coherenceroles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CoherenceRoles that match those selectors.
func (c *coherenceRoles) List(opts metav1.ListOptions) (result *v1.CoherenceRoleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CoherenceRoleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("coherenceroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested coherenceRoles.
func (c *coherenceRoles) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("coherenceroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a coherenceRole and creates it.  Returns the server's representation of the coherenceRole, and an error, if there is any.
func (c *coherenceRoles) Create(coherenceRole *v1.CoherenceRole) (result *v1.CoherenceRole, err error) {
	result = &v1.CoherenceRole{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("coherenceroles").
		Body(coherenceRole).
		Do().
		Into(result)
	return
}

// Update takes the representation of a coherenceRole and updates it. Returns the server's representation of the coherenceRole, and an error, if there is any.
func (c *coherenceRoles) Update(coherenceRole *v1.CoherenceRole) (result *v1.CoherenceRole, err error) {
	result = &v1.CoherenceRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("coherenceroles").
		Name(coherenceRole.Name).
		Body(coherenceRole).
		Do().
		Into(result)
	return
}

// Delete takes name of the coherenceRole and deletes it. Returns an error if one occurs.
func (c *coherenceRoles) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("coherenceroles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *coherenceRoles) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("coherenceroles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched coherenceRole.
func (c *coherenceRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CoherenceRole, err error) {
	result = &v1.CoherenceRole{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("coherenceroles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
